<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.5.3" />
    <ProjectReference Include="..\DevEval.Application\DevEval.Application.csproj" />
    <ProjectReference Include="..\DevEval.ORM\DevEval.ORM.csproj" />
  </ItemGroup>

</Project>
